### ISSUE TITLE
Mousedown event get wrong

### ISSUE THREAD

**Issue by Qquanwei** [jonhni/react-drawable-canvas#5]
mousedown event instance havn't targetTouchs properity, would be throw a error 
`Uncaught TypeError: Cannot read property '0' of undefined`

**Comment by AndersCan** [comment]
@jonhni will this be implemented in the next release?

**Comment by jonhni** [comment]
@Qquanwei @AndersCan Feel free to submit a pull request ;)

**Comment by Qquanwei** [comment]
@AndersCan Would you like to submit a PR ?
